name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug GitHub Context
      run: echo "Running on ref ${{ github.ref }} in repository ${{ github.repository }}"

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Verify AWS Credentials
      run: |
        echo "Verifying AWS credentials..."
        aws sts get-caller-identity

    - name: Debug Environment Variables
      run: |
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "AWS_SECRET_ACCESS_KEY is set but masked"

    - name: List repository files
      run: ls -la

    - name: Zip application files
      run: |
        echo "Zipping application files..."
        zip -r app.zip .
        ls -lah app.zip

    - name: Verify ZIP File
      run: |
        echo "Verifying ZIP file contents..."
        unzip -l app.zip

    - name: Export AWS Credentials
      run: |
        echo "Exporting AWS credentials to environment variables..."
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV
        echo "AWS_REGION=eu-north-1" >> $GITHUB_ENV

    - name: Debug AWS Environment Variables
      run: env | grep AWS_

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v20
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: "quantumsafe-encryption-tool"
        environment_name: "quantumsafe-encryption-tool"
        version_label: ${{ github.sha }}
        region: eu-north-1
        deployment_package: "./app.zip"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: eu-north-1

    - name: Confirm Deployment Success
      run: echo "Deployment to Elastic Beanstalk completed successfully."
