jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - run: |

        echo "API Key: ${{ secrets.AWS_ACCESS_KEY_ID }}"
        echo "API Key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}"
